### Imports

In [1]:
import os
os.environ["http_proxy"] = "http://dahernandez:34732b8f774d6def@ohswg.ottawahospital.on.ca:8080"
os.environ["https_proxy"] = "http://dahernandez:34732b8f774d6def@ohswg.ottawahospital.on.ca:8080"
import pydicom
import subprocess
from pathlib import Path
import nibabel as nib
from dipy.io import read_bvals_bvecs
from dipy.core.gradients import gradient_table
from dipy.io.image import load_nifti, save_nifti
from dipy.reconst.shm import CsaOdfModel
from dipy.direction import peaks_from_model
from dipy.data import default_sphere
from dipy.segment.mask import median_otsu
from dipy.viz import actor, colormap, has_fury, window
from dipy.tracking.stopping_criterion import ThresholdStoppingCriterion
from dipy.reconst.dti import TensorModel
from dipy.tracking.utils import random_seeds_from_mask
from dipy.tracking.streamline import Streamlines
from dipy.tracking.tracker import eudx_tracking
from dipy.io.stateful_tractogram import Space, StatefulTractogram
from dipy.io.streamline import save_trk
from skimage.draw import polygon
from skimage import measure
import matplotlib.pyplot as plt
import numpy as np

### DICOM to NIfTI

In [ ]:
dicom_dir = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/DICOM")
nifti_dir = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/NIfTI")

nifti_dir.mkdir(parents=True, exist_ok=True) # make folder for NIFTI if it doesnt exist yet

cmd = [
    "dcm2niix",
    "-z", "y",
    "-f", "%p_%s",
    "-o", str(nifti_dir),
    str(dicom_dir)
]

subprocess.run(cmd, check=True)

### Functions

In [4]:
def mm_to_voxel(mm_coords, origin, spacing):
    return np.round((mm_coords-origin)/spacing).astype(int)

### Tractography

##### Extract data and perform segmentation

In [5]:
# Define file names
fname = "V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/NIfTI/ep2d_diff_mddw_ISO_1.5MM_6"
nifti_file = fname + ".nii.gz"
bval_file  = fname + ".bval"
bvec_file  = fname + ".bvec"

# Extract data
data, affine, hardi_img = load_nifti(nifti_file, return_img = True)
bvals, bvecs = read_bvals_bvecs(bval_file, bvec_file)

# Make gradient table
gtab = gradient_table(bvals, bvecs = bvecs)

# Make brain mask
data_masked, mask = median_otsu(data, vol_idx=range(data.shape[3]), numpass=1)

##### Create white matter mask with DTI

In [6]:
# Fit the diffusion tensor model
tensor_model = TensorModel(gtab)
tensor_fit = tensor_model.fit(data_masked)

# Get FA map
FA = tensor_fit.fa

# Generate white matter mask using FA threshold
# Typical FA threshold for white matter is between 0.2 - 0.3
white_matter_mask = (FA > 0.25).astype(np.uint8)

##### Use CSA model and peaks_from_model and define stopping criterion

In [7]:
# Using CSA (Constant Solid Angle) model then peaks_from_model
csa_model = CsaOdfModel(gtab, sh_order_max=4)
csa_peaks = peaks_from_model(
    csa_model, data, default_sphere, relative_peak_threshold=0.8, min_separation_angle=45, mask=white_matter_mask
)

# Define stopping criterion
stopping_criterion = ThresholdStoppingCriterion(csa_peaks.gfa, 0.25)

##### Obtain ROI with white matter mask

###### Load in DICOM files included RT struct and MRIs

In [8]:
# Read in folder with ROI struct

Folder = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/ROIs")

CT_File_Names = []
RD_File_Names = []
RP_File_Names = []
RS_File_Names = []
MR_File_Names = []

CT_Files = []
RD_Files = []
RP_Files = []
RS_Files = []
MR_Files = []

for file in Folder.glob("*.dcm"):
    if file.is_file():
        # print(f"Found file: {file.name}")
        try:
            if "CT" in file.name.upper() and pydicom.dcmread(file, stop_before_pixels=True).Modality == 'CT':
                CT_Files.append(pydicom.dcmread(file)) 
                CT_File_Names.append(file)
            elif "RD" in file.name.upper() and pydicom.dcmread(file, stop_before_pixels=True).Modality == 'RTDOSE':
                RD_Files.append(pydicom.dcmread(file))
                RD_File_Names.append(file)
            elif "RP" in file.name.upper() and pydicom.dcmread(file, stop_before_pixels=True).Modality == 'RTPLAN':
                RP_Files.append(pydicom.dcmread(file))
                RP_File_Names.append(file)
            elif "RS" in file.name.upper() and pydicom.dcmread(file, stop_before_pixels=True).Modality == 'RTSTRUCT':
                RS_Files.append(pydicom.dcmread(file))
                RS_File_Names.append(file)
            elif "MR" in file.name.upper() and pydicom.dcmread(file, stop_before_pixels=True).Modality == 'MR':
                MR_Files.append(pydicom.dcmread(file))
                MR_File_Names.append(file)
            else:
                print(f"Unknown DICOM file {file.name}")
        except:
            print(f"Skipped invalid DICOM: {file.name}")

print(f"Found {len(CT_Files)+len(RD_Files)+len(RP_Files)+len(RS_Files)+len(MR_Files)} valid DICOM files")

Found 77 valid DICOM files


###### Load in MRIs and corresponding data

In [10]:
# Load in MRI
Sorted_MR_Files = sorted(MR_Files, key=lambda file: float(file.ImagePositionPatient[2])) # sort files by z-axis. increasing towards the head
# anatomical orientation type (0010,2210) absent so z-axis is increasing towards the head of the patient

MR_Images = np.stack([slice.pixel_array for slice in Sorted_MR_Files], axis = 2) # make 3d matrix in [y x z]
MR_Images = np.transpose(MR_Images, (1, 0, 2)) # make it [x y z]

pixel_spacing = Sorted_MR_Files[0].PixelSpacing # pixel spacing in mm, [y x]
slice_thickness = Sorted_MR_Files[0].SliceThickness # slice thickness in mm [z]
voxel_spacing = np.array([pixel_spacing[1], pixel_spacing[0], slice_thickness]) # [x y z]
origin = np.array(Sorted_MR_Files[0].ImagePositionPatient) # origin in mm [x y z]

In [33]:
pixel_spacing

[1.5, 1.5]

In [34]:
slice_thickness

'1.5'

In [30]:
origin

array([-95.21032371, -97.71157959, -73.09314728])

###### Load ROI mask

In [12]:
# Load in ROI mask

# Define contour sequence (contains contours for all ROIs)
Contour_Sequence = RS_Files[0].ROIContourSequence

# Define list of ROI names
ROI_Names = {ROI.ROINumber: 
             ROI.ROIName for ROI in RS_Files[0].StructureSetROISequence}

Target_Structures = ["GTV"]
Target_Numbers = np.full(len(Target_Structures), np.nan) # pre-allocate Target_Numbers

# Fill in Target_Numbers
for i, structure in enumerate(Target_Structures):
    for Number, Name in ROI_Names.items():
        if structure.upper() == Name.upper():
            Target_Numbers[i] = Number
            break

# Define contour sequence
Contour_Sequence = RS_Files[0].ROIContourSequence

# Pre-allocate to contain all masks
all_masks = []

# Get contour data from every target structure, by verifying ROI number
for i, Number in enumerate(Target_Numbers):
    for ROI in Contour_Sequence:
        if ROI.ReferencedROINumber == Number:
            Contour_Data = ROI.ContourSequence
            break

    # Get contour points and make 3D mask
    # contour_points = np.array([]).reshape(0,3) # pre-allocate matrix of all contour points
    mask = np.zeros(MR_Images[:, :, :].shape) # pre-allocate mask
    for Contour in Contour_Data: # get the contour points in every slice
        contour_points_mm = np.array(Contour.ContourData).reshape(-1, 3) # (n, 3) 3 columns in n rows. in mm
        contour_points_slice = np.array([mm_to_voxel(p, origin, voxel_spacing) for p in contour_points_mm])
        rr, cc = polygon(contour_points_slice[:,1], contour_points_slice[:,0], MR_Images[:, :, 0].shape)
        mask[rr, cc, contour_points_slice[0,2]] = 1

    # Extract surface mesh with marching cubes
    verts, faces, normals, values = measure.marching_cubes(mask, level=0.5) 

    # Append masks to all_masks variable
    all_masks.append(mask)

###### Interpolate if necessary (not developed since not needed I'm pretty sure)

In [15]:
# Interpolate masks if necessary. All masks will have same shape assuming we got them from the same MRI or CT so only need to check one
if all_masks[0].shape == white_matter_mask.shape:
    all_masks_fitted = all_masks
else:
    # They should be the same shape since they should be from the same MRIs
    raise Exception("ROI mask and white matter mask not the same shape. Ensure they are from the same MRIs.")

###### Combine ROI mask and white matter mask

In [17]:
# Combining white matter mask with ROI mask

ROI_white_matter_mask = all_masks_fitted[0].astype(bool) & white_matter_mask.astype(bool) # assuming one mask in all masks

###### Save this combined mask as NIfTI file

In [18]:
# saving with save_nifti
# nah this doesnt work
save_nifti("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/NIfTI_ROIs_test/ROI_WM_mask.nii.gz", ROI_white_matter_mask, affine=affine)

HeaderDataError: data dtype "bool" not supported

###### Trying another way to get ROI mask with RT-Utils

In [24]:
from rt_utils import RTStructBuilder
from pathlib import Path
import nibabel as nib

# Paths
dicom_mri_dir = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/ROIs")  # Folder with MR DICOM slices (not the RTSTRUCT)
rtstruct_path = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/ROIs_test/RS1.2.752.243.1.1.20250620111917393.3000.17511.dcm")  # RTSTRUCT file

# Load RTStruct
rtstruct = RTStructBuilder.create_from(dicom_series_path=dicom_mri_dir, rt_struct_path=rtstruct_path)

# List available ROI names
print(rtstruct.get_roi_names())

# Choose one ROI to convert to NIfTI mask
roi_name = "GTV"
roi_mask = rtstruct.get_roi_mask_by_name(roi_name)  # 3D binary numpy array

external_mask = rtstruct.get_roi_mask_by_name("External")

# Combining roi and white matter masks
roi_wm_mask = roi_mask.astype(bool) & white_matter_mask.astype(bool)

# Save to NIfTI
nifti_path = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/NIfTI_ROIs_test/gtv_wm_mask.nii.gz")
nib.save(nib.Nifti1Image(roi_wm_mask.astype('uint8'), affine=affine), nifti_path)

['GTV', 'External']


In [26]:
rtstruct.series_data[0].Columns

128

In [27]:
rtstruct.series_data[0].Rows

128

In [28]:
len(rtstruct.series_data)

76

In [29]:
rtstruct.series_data[0].ImagePositionPatient

[-95.210323705368, -97.711579587231, -73.093147277832]

In [31]:
rtstruct.series_data[0].PixelSpacing

[1.5, 1.5]

In [53]:
rtstruct.series_data[0].ImageOrientationPatient[:3]

['0.99945021689902', '0.03315514953226', '0']

In [54]:
rtstruct.series_data[0].ImageOrientationPatient[3:]

['-0.0331551495323', '0.99945021689902', '0']

In [57]:
row_direction = np.array(rtstruct.series_data[-1].ImageOrientationPatient[:3])

In [58]:
column_direction = np.array(rtstruct.series_data[-1].ImageOrientationPatient[3:])

In [59]:
np.cross(row_direction, column_direction)

array([ 0., -0.,  1.])

In [60]:
slice_direction = np.cross(row_direction, column_direction)

In [61]:
np.dot(slice_direction, rtstruct.series_data[-1].ImagePositionPatient)

np.float64(39.40685272216823)

In [62]:
(39.40685272216823 -(-73.09314727783244))/(len(rtstruct.series_data)-1)

1.500000000000009

In [63]:
linear = np.identity(3, dtype=np.float32)
linear[0, :3] = row_direction / pixel_spacing[0]
linear[1, :3] = column_direction / 1.5
linear[2, :3] = slice_direction / 1.5

In [65]:
offset = np.array(rtstruct.series_data[0].ImagePositionPatient)

mat = np.identity(4, dtype=np.float32)
mat[:3, :3] = linear
mat[:3, 3] = offset.dot(-linear.T)

In [66]:
mat

array([[ 6.6630012e-01,  2.2103433e-02,  0.0000000e+00,  6.5598412e+01],
       [-2.2103433e-02,  6.6630012e-01,  0.0000000e+00,  6.3000763e+01],
       [ 0.0000000e+00, -0.0000000e+00,  6.6666669e-01,  4.8728767e+01],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]],
      dtype=float32)

In [ ]:
array([-95.21032371, -97.71157959, -73.09314728]) # what i got for ImagePositionPatient (origin)

In [25]:
rtstruct.series_data[0]

Dataset.file_meta -------------------------------
(0002,0000) File Meta Information Group Length  UL: 282
(0002,0001) File Meta Information Version       OB: b'\x00\x01'
(0002,0002) Media Storage SOP Class UID         UI: MR Image Storage
(0002,0003) Media Storage SOP Instance UID      UI: 1.3.12.2.1107.5.2.32.35382.2021040910524826717804908
(0002,0010) Transfer Syntax UID                 UI: Implicit VR Little Endian
(0002,0012) Implementation Class UID            UI: 1.2.826.0.1.3680043.1.2.100.8.40.1101.0
(0002,0013) Implementation Version Name         SH: 'DicomObjects.NET'
(0002,0100) Private Information Creator UID     UI: 1.2.826.0.1.3680043.1.2.100.8.40.1101.0
(0002,0102) Private Information                 OB: b'DicomObjects.NET'
-------------------------------------------------
(0008,0005) Specific Character Set              CS: 'ISO_IR 100'
(0008,0008) Image Type                          CS: ['ORIGINAL', 'PRIMARY', 'DIFFUSION', 'NONE', 'ND', 'NORM']
(0008,0012) Instance Crea

In [ ]:
# Check what image struct references
import pydicom

ds = pydicom.dcmread("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/ROIs_test/RS1.2.752.243.1.1.20250620111917393.3000.17511.dcm")

for ref in ds.ReferencedFrameOfReferenceSequence:
    study = ref.RTReferencedStudySequence[0]
    series = study.RTReferencedSeriesSequence[0]
    print("Referenced Series UID:", series.SeriesInstanceUID)

In [ ]:
# Check SeriesInstanceUID from folder of MR DICOMs

from pathlib import Path
import pydicom

# Set this to your MR DICOM folder
mr_dicom_dir = Path("V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/ROIs")

# Find the first valid file in that folder
for dicom_file in mr_dicom_dir.glob("*"):
    try:
        ds = pydicom.dcmread(dicom_file, stop_before_pixels=True)
        series_uid = ds.SeriesInstanceUID
        print(f"Found SeriesInstanceUID: {series_uid}")
        break  # You only need one file from the series
    except Exception as e:
        print(f"Skipping {dicom_file.name}: {e}")

##### Generate seeds 

In [19]:
# Generating seeds
seeds = random_seeds_from_mask(ROI_white_matter_mask, affine, seeds_count=1, seed_count_per_voxel=True)

##### Use EuDX tracking to create streamlines

In [20]:
# Using EuDX tracking for now. 
# Initialization of eudx_tracking. The computation happens in the next step.
streamlines_generator = eudx_tracking(
    seeds, stopping_criterion, affine, step_size=0.5, pam=csa_peaks
)
# Generate streamlines object
streamlines = Streamlines(streamlines_generator)

##### Show tracks

In [26]:
interactive = True

if has_fury:
    # Prepare the display objects.
    color = colormap.line_colors(streamlines)

    streamlines_actor = actor.line(
        streamlines, colors=colormap.line_colors(streamlines)
    )

    roi_actor = actor.contour_from_roi(
        roi_wm_mask, affine=affine, opacity=0.5, color=(1, 0, 0) # red
    ) 

    roi_actor_external = actor.contour_from_roi(
        external_mask, affine=affine, opacity=0.5, color=(0, 0, 1) # blue
    ) 

    # Create the 3D display.
    scene = window.Scene()
    scene.add(streamlines_actor)
    scene.add(roi_actor)
    scene.add(roi_actor_external)

    # Save still images for this static example. Or for interactivity use
    # window.record(scene=scene, out_path="tractogram_EuDX.png", size=(800, 800))
    if interactive:
        window.show(scene)

In [19]:
interactive = True

if has_fury:
    # Prepare the display objects.
    # color = colormap.line_colors(streamlines)

    # streamlines_actor = actor.line(
    #     streamlines, colors=colormap.line_colors(streamlines)
    # )

    # roi_actor = actor.contour_from_roi(
    #     roi_wm_mask, affine=affine, opacity=0.25, color=(1, 0, 0) # red
    # ) 

    # roi_actor2 = actor.contour_from_roi(
    #     ROI_white_matter_mask, affine=affine, opacity=0.25, color=(0, 0, 1) # blue
    # ) 

    # roi_actor3 = actor.contour_from_roi(
    #     test, affine=affine, opacity=0.75, color=(0, 1, 0) # green
    # ) 

    roi_actor = actor.contour_from_roi(
        all_masks_fitted[0], affine=affine, opacity=0.75, color=(1, 0, 0) # red
    ) 

    roi_actor2 = actor.contour_from_roi(
        roi_mask, affine=affine, opacity=0.75, color=(0, 0, 1) # blue
    ) 

    roi_actor3 = actor.contour_from_roi(
        np.where(all_masks_fitted[0] != roi_mask, 1, 0), affine=affine, opacity=0.5, color=(0, 1, 0) # green
    ) 

    # Create the 3D display.
    scene = window.Scene()
    # scene.add(roi_actor3)
    scene.add(roi_actor2)
    scene.add(roi_actor)

    # Save still images for this static example. Or for interactivity use
    # window.record(scene=scene, out_path="tractogram_EuDX.png", size=(800, 800))
    if interactive:
        window.show(scene)

In [ ]:
print(np.where(roi_wm_mask[:,:,:] != ROI_white_matter_mask[:,:,:]))

test = np.where(roi_wm_mask[:,:,:] != ROI_white_matter_mask[:,:,:], 1, 0)

In [ ]:
np.where(test == 1)

##### Save TRK file

In [ ]:
sft = StatefulTractogram(streamlines, hardi_img, Space.RASMM)
save_trk(sft, "V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/NIfTI/tractogram_EuDX.trk", streamlines)

### WMPL

In [ ]:
from dipy.io.image import load_nifti, save_nifti
from dipy.tracking.utils import get_flexi_tvis_affine, path_length
import nibabel as nib
import os
os.environ["http_proxy"] = "http://dahernandez:34732b8f774d6def@ohswg.ottawahospital.on.ca:8080"
os.environ["https_proxy"] = "http://dahernandez:34732b8f774d6def@ohswg.ottawahospital.on.ca:8080"

# set the path to the data
basedir = "V:/Common/Staff Personal Folders/DanielH/DICOM_Files/TractographyPatient/Patient 1/" # folder containing nifti file with roi and trk file with streamlines

# set the path to the roi and the streamlines (trk)
roi_path = ''